# Building Dockerfile from scratch

# NOTE: You'll find how to run this with other info in README.md

# Using official 'node' image with Alpine branch
FROM node:alpine:3.18.4

# This app will listen on port 3000
EXPOSE 3000

