services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=9081
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: flask
      dockerfile: builder
    # flask requires SIGINT to stop gracefully
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9081
    volumes:
      - 
    depends_on:
      -

  mongo:
    image: mongo