services:
  web:
    image: nginx
    # create a volume, maps nginx.conf file from the host to /tmp/ within the container
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    # nginx config uses this as a variable to set up the reverse proxy  
    environment:
      - FLASK_SERVER_ADDR=backend:9091
    # variable substitution on config file; reading /tmp.. and writing the result to /etc..
    # 'daemon off -g' starts Nginx server in the background allowing to pass directives to Nginx as if they were in config file.   
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports: 
      - 8080:80
    depends_on:
      - backend

  backend:
    build:
      # when building using Dockerfile located in flask target build stage "dev-envs"
      context: flask
      target: dev-envs
    # Flask requires SIGINT to shutdown gracefuly. (Compose default is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    # defining a volume for sharing Docker's daemon socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongo
# db
  mongo:
    image: mongo