services:
  web:
    image: nginx
    volumes:
      - 
    environment:
      -
    command:
    ports: 80:80
    depends_on:
      - backend

  backend:
    build:
      context: flask
      target: dev-envs
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9081