services:
  web:
    image: nginx
    # create a volume, maps nginx.conf file from the host to /tmp/ within the container
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    # nginx config uses this as a variable to set up the reverse proxy  
    environment:
      - FLASK_SERVER_ADDR=backend:9081
    command:
    ports: 
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      # when building using Dockerfile located in flask target build stage "dev-envs"
      context: flask
      target: dev-envs
    # Flask requires SIGINT to shutdown gracefuly. (Compose default is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9081
    # defining a volume for sharing Docker's daemon socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongo

  mongo:
    image: mongo