services:
  web:
    image: nginx
    volumes:
      -
    # nginx config uses this as a variable to set up the reverse proxy  
    environment:
      - FLASK_SERVER_ADDR=backend:9081
    command:
    ports: 
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: flask
      target: dev-envs
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9081
    depends_on:
      - mongo

  mongo:
    image: mongo