# no version needed as of 2020
# 2.x and 2.x features are supported

# this compose sample uses HTML static site from https://startbootstrap.com/themes/agency/

services:
  proxy:
    build:
      # building Docker file in current dirrectory
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx-custom